spring:
  kafka:
    bootstrap-servers: 127.0.0.1:29092

    admin:
      auto-create: false

app:
  kafka:
    auto-create-topics: false
    ensure-at-startup: false

kafka:
  ssl:
    enabled: false
    security-protocol: SASL_SSL
    sasl-mechanism: AWS_MSK_IAM
    sasl-jaas-config: software.amazon.msk.auth.iam.IAMLoginModule required;
    sasl-client-callback-handler-class: software.amazon.msk.auth.iam.IAMClientCallbackHandler

  producer:
    enabled: false
    bootstrap-servers: 127.0.0.1:29092

  consumer:
    enabled: false
    bootstrap-servers: 127.0.0.1:29092
    trusted-packages: "org.example.order.*,java.time.*,java.util.*,java.lang.*"
    option:
      max-fail-count: 1
      max-poll-records: 1000
      fetch-max-wait-ms: 500
      fetch-max-bytes: 52428800
      max-poll-interval-ms: 300000
      idle-between-polls: 0
      auto-offset-reset: "earliest"
      enable-auto-commit: false

  topic:
    - category: ORDER_LOCAL
      name: "local-order-local"
    - category: ORDER_API
      name: "local-order-api"
    - category: ORDER_CRUD
      name: "local-order-crud"
    - category: ORDER_REMOTE
      name: "local-order-remote"
    - category: ORDER_DLQ
      name: "local-order-dead-letter"
    - category: ORDER_ALARM
      name: "local-order-alarm"
